version: '3.9'

services:
  api:
    container_name: gh-test-api
    image: node:20
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    command: ['yarn', 'dev']
    ports:
      - "8000:8000"
